export const qualificationLabels = {
  others: "Others",
  hsc: "HSC",
  ba: "B.A",
  msc: "M.Sc",
  mba: "M.B.A",
  bcom: "B.Com",
  ssc: "SSC",
  bsc: "B.Sc",
  bpharm: "B.Pharm",
  hafiz: "Hafiz",
  diploma: "Diploma",
  engineer: "Engineer",
  "ba llb": "B.A LLB",
  iti: "ITI",
  mcom: "M.Com",
  bba: "B.B.A",
  "below ssc": "Below SSC",
  ma: "M.A",
  bca: "B.C.A",
  doctor: "Doctor",
  mpt: "M.P.T",
  phd: "Ph.D",
  mphil: "M.Phil",
  ielts: "IELTS",
  pg: "P.G",
  mca: "M.C.A",
  bed: "B.Ed",
  bcs: "B.C.S",
  bpt: "B.P.T",
  mpharm: "M.Pharm",
  ca: "C.A",
};
